name: Kernel CI - Munch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl zip bc bison flex make clang lld llvm libssl-dev python3

      - name: Run build
        run: |
          chmod +x build.sh
          bash build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: munch-kernel
          path: out/